name: Build Extension (Simple)

on:
  push:
    branches: [ main, master, feat/manifestV3 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'
        cache: 'yarn'
        
    - name: Setup Python for node-sass
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile --ignore-engines --network-timeout 600000 || yarn install --network-timeout 600000
      env:
        PYTHON: python3
        npm_config_python: python3
      
    - name: Build extension
      run: yarn build
      
    - name: Package extension
      run: |
        cd build
        zip -r ../sync-my-cookie-extension.zip .
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sync-my-cookie-extension
        path: sync-my-cookie-extension.zip
        retention-days: 30